
# toolset

CC = $(CROSSDIR)/bin/ia16-elf-gcc
AS = $(CROSSDIR)/bin/ia16-elf-gcc
LD = $(CROSSDIR)/bin/ia16-elf-ld
NM = $(CROSSDIR)/bin/ia16-elf-nm
AR = $(CROSSDIR)/bin/ia16-elf-ar
ST = $(CROSSDIR)/bin/ia16-elf-strip
NA = nasm

CP = cp
MV = mv


# defines

CCOPT = -Os -ffreestanding -march=i8086 -mtune=i8086 -mcmodel=tiny -std=gnu99
CCERR = -Wnull-dereference -Wall -W -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wredundant-decls -Wuninitialized -Winline -Wswitch -Wshadow -Wchar-subscripts -Wwrite-strings -Wdiscarded-qualifiers -Wcast-align -Wcast-qual -Wno-sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body

ASOPT = -Os -mtune=i8086
ASERR = -Wnull-dereference -Wall -W -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wredundant-decls -Wuninitialized -Winline -Wswitch -Wshadow -Wchar-subscripts -Wwrite-strings -Wdiscarded-qualifiers -Wcast-align -Wcast-qual -Wno-sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body


# toolset flags

CCFLAGS = -c $(CCOPT) $(CCERR) -I$(TOPDIR)/src/include
ASFLAGS = -c $(ASOPT) $(ASERR) -I$(TOPDIR)/src/include

